version: '3.1'

services:
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=postgres   
            - POSTGRES_DB=jus_qa  
        ports:
            - "5432:5432"
        volumes:
         - ./pgdata:/var/lib/postgresql/data 
             
    pgadm:
        image: dpage/pgadmin4
        container_name: pgadm
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=postgres
        ports:
             - "5050:80"
       
networks:
   app:
    driver: bridge


